name: Build and deploy docs

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCS_IMAGE: kokkos-docs
      DOCS_DIRECTORY: ${{ github.workspace }}/docs
    steps:
      - uses: actions/checkout@v7
      - name: Build documentation container
        run: docker build --file Containerfile --tag "${DOCS_IMAGE}" .
      - name: Build documentation
        run: |
          docker run --rm \
            --user "$(id -u):$(id -g)" \
            --env HOME=/tmp \
            --volume "${GITHUB_WORKSPACE}:/workspace" \
            --workdir /workspace/docs \
            "${DOCS_IMAGE}" \
            make html
      - name: Upload documentation as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v5.0.0
        with:
          name: github-pages
          path: ${{ env.DOCS_DIRECTORY }}/generated_docs

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5.0.1
